In [3]:
import numpy as np

## numpy array

In [11]:
benimListem = [20,30,40]

In [13]:
type(benimListem)

list

In [15]:
np.array(benimListem)

array([20, 30, 40])

In [17]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [19]:
matrixListesi[1][0]

20

In [21]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [24]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [32]:
# range python, arange numpy

## zeros

In [37]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [39]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## linspace

In [50]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [52]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [54]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

## eye

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [71]:
np.random.randn(4)

array([ 0.51232665, -1.16660853,  1.28447041,  0.42821941])

In [73]:
np.random.randn(4,4)

array([[ 1.39824497, -0.51687897, -0.30351977, -0.18262151],
       [ 0.79815597,  0.27716148, -0.19109531, -0.23478554],
       [-1.38223742,  1.67169371, -1.87665346,  0.34305122],
       [ 1.81732692, -0.45960106, -0.9260493 , -1.34789856]])

In [75]:
np.random.randint(1,10) # 1 dahil, 10 exclude

2

In [77]:
np.random.randint(1,10)

3

In [79]:
np.random.randint(1,10,5)

array([4, 1, 1, 4, 2])

In [81]:
benimNumpyDizim = np.arange(30)

In [83]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
benimRandomDizim = np.random.randint(0,100,30)

In [87]:
benimRandomDizim

array([28, 47, 34, 20, 42, 24, 95, 14, 69, 79, 85, 31, 65,  1, 60, 18, 96,
       92, 91, 61,  6,  4, 83, 26, 28, 63, 97,  2, 58, 87])

## numpy dizi methodları

In [91]:
benimNumpyDizim.reshapce(5,5)

AttributeError: 'numpy.ndarray' object has no attribute 'reshapce'

In [93]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [95]:
# 5x5 de 25, 5x6'da 30 aralık var. 30 değere sahip bir diziyi 25 aralığa sığdıramayız.

In [105]:
benimNumpyDizim.min()

0

In [97]:
benimNumpyDizim.max()

29

In [99]:
benimRandomDizim.max()

97

In [107]:
benimRandomDizim.min()

1

In [113]:
benimRandomDizim.argmin()

13

In [115]:
benimRandomDizim.argmax()

26

In [117]:
benimNumpyDizim.shape

(30,)

In [119]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [121]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [123]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## Numpy Operasyonlar

In [126]:
benimDizim = np.arange(0,15)

In [128]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [130]:
benimDizim[5]

5

In [132]:
# listeler 0'dan başlar, numpy arrayler de 0 dan başlar

In [134]:
benimDizim[3:5] 

array([3, 4])

In [136]:
#stop index 5 yapıldığında, 5'i döndürmez

In [138]:
benimDizim[3:8] = -5

In [140]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [142]:
baskaDizi = np.arange(0,24)

In [144]:
slicingDizisi = baskaDizi[4:9] 

In [146]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [148]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [150]:
slicingDizisi = 700

In [152]:
type(slicingDizisi)

int

In [154]:
slicingDizisi = baskaDizi[4:9] 

In [158]:
slicingDizisi [:] = 700

In [160]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [162]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [164]:
ornekDizi = np.arange(0,24)

In [166]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [168]:
ornekDiziKopyasi = ornekDizi.copy()

In [170]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [174]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [178]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [180]:
ornekDiziKopyasiSlicing[:] = 800

In [182]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [184]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [186]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [ ]:
benimListem = [[10,20,30],[20,30,40],[30,40,50]]

In [192]:
benimListem = [[10,20,30],[20,30,40],[30,40,50]]

In [194]:
benimMatrixDizim = np.array(benimListem)

In [196]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

In [198]:
benimMatrixDizim[0]

array([10, 20, 30])

In [200]:
benimMatrixDizim[1][2]

40

In [202]:
benimMatrixDizim[1,2]

40

In [204]:
benimMatrixDizim[1:,2]

array([40, 50])

In [206]:
benimMatrixDizim[2:,2]

array([50])

In [228]:
yeniListe= [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [230]:
yeniMatrix = np.array(yeniListe)

In [232]:
yeniMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [234]:
yeniMatrix[1]

array([ 6,  7,  8,  9, 10])

In [236]:
yeniMatrix[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [238]:
yeniMatrix[[2,0]]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

## operasyonlar

## Operasyonlar

## Operasyonlar

In [248]:
yeniBirDizi = np.random.randint(1,100,20)

In [250]:
yeniBirDizi

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 22, 51,  5, 60,  5, 30,
       29, 21, 24])

In [252]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
       False, False])

In [254]:
yeniBirDizi

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 22, 51,  5, 60,  5, 30,
       29, 21, 24])

In [256]:
sonucDizisi = yeniBirDizi > 24

In [258]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
       False, False])

In [260]:
yeniBirDizi

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 22, 51,  5, 60,  5, 30,
       29, 21, 24])

In [262]:
yeniBirDizi[sonucDizisi] #1

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 51, 60, 30, 29])

In [264]:
yeniBirDizi

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 22, 51,  5, 60,  5, 30,
       29, 21, 24])

In [266]:
yeniBirDizi[yeniBirDizi>24] #2

array([94, 94, 62, 76, 58, 29, 70, 27, 29, 39, 78, 51, 60, 30, 29])

In [270]:
sonDizi = np.arange(0,24)

In [272]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [274]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [276]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [278]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [280]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [284]:
sonDizi / sonDizi # 0/0 nan uyarı verdi

/var/folders/j0/bf4kc2qs1nq03wpsvxy916fm0000gn/T/ipykernel_7721/1614751826.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi # 0/0 nan uyarı verdi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [286]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [288]:
np.max(sonDizi)

23

In [290]:
np.min(sonDizi)

0